:sectnums:
:toclevels: 3
:toc: preamble
:showtitle:

= Introduction

North Richmond Street, being blind, was a quiet street except at the hour when the Christian Brothers’ School set the boys free. An uninhabited house of two storeys stood at the blind end, detached from its neighbours in a square ground. The other houses of the street, conscious of decent lives within them, gazed at one another with brown imperturbable faces.

The former tenant of our house, a priest, had died in the back drawing-room. Air, musty from having been long enclosed, hung in all the rooms, and the waste room behind the kitchen was littered with old useless papers. Among these I found a few paper-covered books, the pages of which were curled and damp: The Abbot, by Walter Scott, The Devout Communicant and The Memoirs of Vidocq. I liked the last best because its leaves were yellow. The wild garden behind the house contained a central apple-tree and a few straggling bushes under one of which I found the late tenant’s rusty bicycle-pump. He had been a very charitable priest; in his will he had left all his money to institutions and the furniture of his house to his sister.

When the short days of winter came dusk fell before we had well eaten our dinners. When we met in the street the houses had grown sombre. The space of sky above us was the colour of ever-changing violet and towards it the lamps of the street lifted their feeble lanterns. The cold air stung us and we played till our bodies glowed. Our shouts echoed in the silent street. The career of our play brought us through the dark muddy lanes behind the houses where we ran the gauntlet of the rough tribes from the cottages, to the back doors of the dark dripping gardens where odours arose from the ashpits, to the dark odorous stables where a coachman smoothed and combed the horse or shook music from the buckled harness. When we returned to the street light from the kitchen windows had filled the areas. If my uncle was seen turning the corner we hid in the shadow until we had seen him safely housed. Or if Mangan’s sister came out on the doorstep to call her brother in to his tea we watched her from our shadow peer up and down the street. We waited to see whether she would remain or go in and, if she remained, we left our shadow and walked up to Mangan’s steps resignedly. She was waiting for us, her figure defined by the light from the half-opened door. Her brother always teased her before he obeyed and I stood by the railings looking at her. Her dress swung as she moved her body and the soft rope of her hair tossed from side to side.

Every morning I lay on the floor in the front parlour watching her door. The blind was pulled down to within an inch of the sash so that I could not be seen. When she came out on the doorstep my heart leaped. I ran to the hall, seized my books and followed her. I kept her brown figure always in my eye and, when we came near the point at which our ways diverged, I quickened my pace and passed her. This happened morning after morning. I had never spoken to her, except for a few casual words, and yet her name was like a summons to all my foolish blood.
