:sectnums:
:toclevels: 3
:toc: preamble
:showtitle:

= Background, Installation, and Hardware

The Environmental Orb is display technology designed to communicate current levels of resource use in buildings to occupants in order to encourage greater awareness and motivation to conserve. A wifi enabled bulb receives real-time data collected from monitoring equipment installed in the building. This bulb glows different colors and with different pulsing patterns to communicate whether current levels of resource consumption (e.g. electricity, water and/or gas consumption) are high or low relative to typical use at this time of day.

Figure 1. The orb pictured on the left with a circular glass diffuser is installed in the lobby of a college student dormitory. The orb in the middle contains a LIFX bulb in the same housing without a diffuser. The orb on the right is housed in an off-the-shelf and readily available exterior light fixture.

== Orb behavior

Each orb can be configured to display data on two different resources. A “spectrum” of five colors is used to convey levels of current use relative to typical use. An orb owner can select among algorithms used to determine relative use (explained in documentation). However, as an example, electricity might be configured to display a rapid pulsing red (emulating heartbeat) when electricity use unusually high and then move down through a spectrum from red → orange → yellow → yellowish green → green. In this scenario, green with slow pulsing represents unusually low level of use and yellow with intermediate pulsing represents typical use. If the orb is configured to display two resources (for example water as well as electricity), than a distinct five color and pulsing spectrum is used for the second variable.

Orbs are an example of “ambient feedback” — experiential feedback within occupied spaces that communicates limited and potentially subliminal information that requires low cognitive processing. We have therefore restricted use of the orbs to displaying information that conveys current use relative to typical use. In contrast, digital signage provides a context for publicly displaying a much richer set of content over a broad range of scales.

== History

Several generations of orb technology have been developed by students and faculty at Oberlin College with grant support to Oberlin College from the U.S. EPA (grant#XXX) and the Great Lakes Protection Fund (grant#XXX). The first version, developed and deployed in two dorms in 2007 used a modified device called a “link:https://ambientdevices.myshopify.com/products/stock-orb[Stock Orb]”, (which was intended to glow different colors based on the value of stocks). Essentially we added a wifi interface to this existing product and wrote code that allowed these devices to receive numerical data representing current electricity and water use relative to typical use and to translate this data into a color spectrum. We subsequently designed and developed novel orb technology using the open-source https://www.arduino.cc/[Arduino] hardware and software platform. While these technologies worked well at Oberlin and generated considerable interest from others, the lack of complete off-the-shelf hardware and software created a barrier to adoption by others.

== Current Development

Most recently, the Oberlin dashboard team has developed the version of the orb featured on this website (with support from U.S. EPA grant#XXX received by Lucid Design). This orb takes advantage of the recent development of colored lighting products that can be controlled using wifi. The shift to an off-the-shelf display product makes it far easier for other organizations and communities to adopt the orb as a display technology.

== Data Sources

Environmental Orb is designed to display data on resource flows. Use requires a source of data that is delivered to the orb. This orb software is currently designed to receive data on resource use from a single source, Lucid Design’s “BuildingOS” technology. BuildingOS includes numerous integrations that allow Lucid to access data on resource use in buildings from a wide variety of building automation systems as well as from independent data loggers connected to monitoring devices. The orb software is designed to access data from Lucid customers using Lucid’s application program interface (API). Currently, you must be a Lucid customer to use the environmental orb software. In future environmental orb technology may be enhanced to also gather data from other sources

== Orb Display Devices

In the last few years a number of companies have begun to market LED bulbs that allow a user to wirelessly control color, intensity and patterns of display, generally through phone applications. Some of these products, such as the http://www2.meethue.com/en-us/about-hue[Philips Hue], require a separate interface between the application and the lighting device. We choose to integrate with bulb technology manufactured by https://www.lifx.com/[LIFX] because each bulb directly communicates with local internet by WiFi. We have collaborated with LIFX to develop our Environmental Orb software as a recognized integration with their bulbs. The Environmental Orb software communicates with LIFX software to recognize the bulbs you register with them and allows you to configure these bulbs as orbs. The pathway by which data flow to your orb are as follows: monitoring device in buildings → datalogger or building automation system → BuildingOS → our orb server → LIFX server → host organization’s local wifi network → bulb. We have tested the most recent LIFX bulbs functioning as orbs in enclosed cases, allowing them to run continuously for many months. We are pleased with their performance. In the future it is possible that we may modify the software to display on other devices.

== Fixtures and Enclosures

LIFX bulbs have a standard bulb screw base and can therefore be directly used in a very wide variety of existing consumer and commercial fixtures. However, in many public applications it may be useful or necessary to protect these intriguing devices from theft and vandalism. The newest LIFX bulbs fit in a wide variety of standard enclosures. For example, we have recently been experimenting with the use of a water and vapor tight enclosure often used in industrial spaces including on ships (see figure 1 and https://www.amazon.com/gp/product/B000A79I10/ref=oh_aui_search_detailpage?ie=UTF8&psc=1[link here]). These are somewhat rugged and can be made somewhat tamperproof. The custom developed fixtures currently used in Oberlin College dorms are made from a very rugged commercial aluminum lighting base, a glass diffuser and plastic plate, a special ordered Lexan dome and tamperproof screws that hold the dome on (see below). After nearly six years of installation we have experience no theft or tampering of electronics in this housing (we did have one spray painted and another dome was deeply scratched with a knife).

== Orb Location

As “ambient technology” it is important that the orb be placed in prominent location that building occupants experience on a regular basis. We often use the phrase “in your face, in your space” as a general statement describing desired location. For example, in Oberlin dormitories we place orbs displaying whole-dorm resource use at eye-level in lobbies or stairwells that all students experience each time they enter the dorm. For orbs displaying resource used by individual floors or wings of dorms we have often placed them immediately adjacent to bathrooms -- locations that every student regularly walks by multiple times a day. The orbs DO cast light but in most interior locations white building lights may overwhelm the signal. We suggest that before a permanent location is selected those involved in the selection process should observe, experiment with a mobile fixture and survey building occupants. ADA regulations are an important consideration; fixtures that protrude from walls and can potentially affect mobility in a wheelchair are subject to such regulation.

== Signage

=== Algorithms to determine color
There are a variety of different ways that typical use and relative use can be determined and translated into color patterns. Since Environmental Orbs were first created at Oberlin in 2007, several different approaches have been taken. In all cases typical use has been calculated for a given hour of the day by considering the average rate of use at the same hour of the day for similar days in the recent past. So, for example, consider an orb that is displaying data for 6:35 pm on a Wednesday evening in a building for which patterns and magnitudes of electricity use are expected to be similar on weekdays and different on weekends. Assume that the previous 5 days of comparable data have been selected as the typical use interval. First, a set of data for average hourly rate of use (kW) are extracted from a database between 6:00-7:00 pm for the previous 5 weekdays (in this example M and Tu of this week and W, Th and F of the prior week). To understand the rationale for the method currently used by Environmental Orb to calculate typical use (and relative use) it is useful to consider the algorithm originally used.

=== Original orb color algorithm
An average (or alternatively median) of the 5 data points is taken. Relative use is then calculated as the ratio of the current rate of use at this minute (kW) to the average (or median) of the 5 data points. The orb color spectrum is then based on the value of this ratio: red (ratio > 2) → orange ( 2 > ratio > 1.5) → yellow (1.5 > ratio > 0.75) → greenish/yellow (0.75 > ratio > 0.5) → green (0.5 > ratio). This approach is intellectually satisfying because it is easy to interpret and explain: the orb is red if current use is greater than twice typical use; it is green if current use is less than half of typical use; it is yellow if similar to typical use; it is intermediate colors if between these.

=== Problem with original color algorithm
The problem with the simple and elegant algorithm described above is that it leads to different orb responses to occupant behavior (and changing environmental conditions) in different types of buildings. This problem relates to “baseload” which is defined as the minimum rate of resource consumption over a time period (in our example, baseload is equal to the smallest number in the set of 5 data points used to estimate typical use). A high baseload occurs in buildings that have mechanical equipment such as refrigerators, pumps or server computers that are in continuous use. Consider two buildings, one with high electricity baseload and one with low baseload. Assume that discretionary electricity use (the additional electricity used above baseload) is identical in these two buildings. If discretionary use is much less than baseload use than the original orb algorithm will tend to produce a relative use ratio that stays very close to 1; this orb will likely display yellow throughout the period. In contrast, the building with low baseload will generate a ratio that varies from 0.5 to above 2; in response to the same variability in occupants behavior within the building, this building’s orb will travel through the full spectrum of five colors.

=== Baseline adjusted orb color algorithm
One corrective option we experimented with is to subtract the baseload before calculating relative use. Specifically, this considers the 5 data points representing typical use and the current value and subtracts the smallest of these from all the other numbers. The relative value can then be calculated from these baseload-adjusted numbers in a way that is identical to that described above. The adjusted orb behavior can be explained to building occupants in a way that is very similar to the original explanation; the orb is red if current use is greater than twice typical discretionary use, (the word discretionary is added to imply use above baseline).

=== Current color algorithm
Even with the baseline adjustment, different buildings may exhibit different degrees of “spikiness” in resource consumption. A building with spiky use patterns results in an orb that alternates between colors representing highest and lowest use. The current algorithm is optimized to compel the orb to spend approximately the same amount of time in each of its five colors. The way that this is accomplished is by ordering the typical use data from lowest to highest and then determining relative use based on where the current value falls in this sequence. For example, imagine the value of the five data points collected are 62.5, 63, 65, 66, 66.5 kW and the current reading at 6:35 pm is 64 kW. Because the current reading falls second in this list the relative value is calculated as 2/6 (a denominator of six because there are now six points in this list). This algorithm always produces a value that is between (or equal to) 0 and 1. The orb color spectrum is based on the algorithm value: red (value> 0.8) → orange ( 0.8> value> 0.6) → yellow (0.6 > value> 0.4) → greenish/yellow (0.4 > value> 0.2) → green (0.2 > value).
